all: main brute_force

main: main.cpp
	g++ -g -std=c++11 -o main main.cpp

brute_force: brute_force.cpp
	g++ -g -std=c++11 -o brute_force brute_force.cpp

.PHONY: clean

clean:
	rm -f main brute_force
