/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TotalAppealOfAString;

public class App {

    public static void main(String[] args) {
        String s = "aba";
        Solution3 solution3 = new Solution3();
        long result = solution3.appealSum(s);
        System.out.println(result);
    }
}
