/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minimumnumberoftapstoopentowateragarden;

public class App {

    public static void main(String[] args) {
        int n = 5;
        int[] ranges = {3, 4, 1, 1, 0, 0};
        Solution solution = new Solution();
        int res = solution.minTaps(n ,ranges);
        System.out.println(res);
    }
}
