/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AllSubsets;

public class App {
    public static void main(String[] args) {
        int[] nums = {3, 34, 4, 12, 5, 2};
        System.out.println("Bit manipulation:");
        BitManipulationSolution solution1 = new BitManipulationSolution(nums);
        for (int i = 0; i < solution1.subsetSums.size(); i++) {
            System.out.printf("%8d: %s%n", solution1.subsetSums.get(i), solution1.subsets.get(i));
        }

        System.out.println("Backtracking:");
        BacktrackingSolution solution2 = new BacktrackingSolution(nums);
        for (int i = 0; i < solution2.subsetSums.size(); i++) {
            System.out.printf("%8d: %s%n", solution2.subsetSums.get(i), solution2.subsets.get(i));
        }
    }
}
