/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FurthestBuildingYouCanReach;

public class App {
    public static void main(String[] args) {
        int[] heights = {4, 12, 2, 7, 3, 18, 20, 3, 19};
        int bricks = 10;
        int ladders = 2;

        MinHeapSolution minHeapSolution = new MinHeapSolution();
        int result = minHeapSolution.furthestBuilding(heights, bricks, ladders);
        System.out.println(result);
    }
}
