/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LongestPalindromicSubsequence;

public class App {
    public static void main(String[] args) {
        String s = "cbbd";
        OptimizedDPSolution solution = new OptimizedDPSolution();
        int length = solution.longestPalindromeSubseq(s);
        System.out.printf("Longest Palindromic Subsequence length: %d%n", length);
    }
}
