/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EggDropping;

public class App {
    public static void main(String[] args) {
        int k = 2, n = 6;

        DPSolution solution1 = new DPSolution();
        int res1 = solution1.superEggDrop(k, n);
        System.out.println(res1);
    }
}
