/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TravellingSalesmanProblem;

public class App {
    public static void main(String[] args) {
        int[][] dist = {
                {0, 10, 15, 20},
                {10, 0, 25, 25},
                {15, 25, 0, 30},
                {20, 25, 30, 0},
        };
        DPSolution solution = new DPSolution();
        int result = solution.shortestRoute(dist);
        System.out.printf("Shortest path: %d%n", result);
    }
}
