/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package findthekthlargestintegerinthearray;

public class App {
    public static void main(String[] args) {
        String[] nums = {"2","21","12","1"};
        int k = 3;
        QuickSelectSolution quickSelectSolution = new QuickSelectSolution();
        String res = quickSelectSolution.kthLargestNumber(nums, k);
        System.out.println(res);
    }
}
