tcp_server: tcp_server.c
	cc -Wall -o tcp_server -std=gnu99 tcp_server.c
tcp_client: tcp_client.c
	cc -Wall -o tcp_client -std=gnu99 tcp_client.c
udp_server: udp_server.c
	cc -Wall -o udp_server -std=gnu99 udp_server.c
udp_client: udp_client.c
	cc -Wall -o udp_client -std=gnu99 udp_client.c
addrinfo_tcp_server: addrinfo_tcp_server.c
	cc -Wall -o addrinfo_tcp_server -Wall -std=gnu99 addrinfo_tcp_server.c
