/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ShortestBridge;

public class App {
    public static void main(String[] args) {
        int[][] grid = {
                {0,0,0,0,0,0},
                {0,1,0,0,0,0},
                {1,1,0,0,0,0},
                {1,1,0,0,0,0},
                {0,0,0,0,0,0},
                {0,0,1,1,0,0},
        };

        GraphSolution solution = new GraphSolution();
        int distance = solution.shortestBridge(grid);
        System.out.printf("Shortest bridge: %d%n", distance);
    }
}
