/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FindMinimumTimeToFinishAllJobs;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] jobs = {1,2,4,7,8};
        int k = 2;

        DPSolution solution = new DPSolution();
        int result = solution.minimumTimeRequired(jobs, k);
        System.out.printf("minimum possible maximum working time of assiging %s to %d workers: %d%n",
                Arrays.toString(jobs), k, result);
    }
}
