/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PartitionArrayIntoTwoArraysToMinimizeSumDifference;

public class App {
    public static void main(String[] args) {
    }
}
