options = -g -std=c++11 -Wall -pipe

NumberOfDiscIntersections: NumberOfDiscIntersections.cpp
	g++ $(options) -o NumberOfDiscIntersections NumberOfDiscIntersections.cpp


.PHONY: clean
clean:
	rm -f NumberOfDiscIntersections
