all: max_diff dp

max_diff: max_diff.c
	gcc -g -std=c99 -o max_diff max_diff.c

subarray_sum: subarray_sum.c
	gcc -g -std=c99 -o subarray_sum subarray_sum.c

.PHONY: clean

clean:
	rm -f max_diff subarray_sum
