/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Arrays;

public class App {
    public static void rotate(int[] nums, int k) {
        k %= nums.length;
        reverse(nums, 0, nums.length - 1);
        reverse(nums, 0, k - 1);
        reverse(nums, k, nums.length - 1);
    }

    private static void reverse(int[] nums, int lo, int hi) {
        while (lo < hi) {
            int tmp = nums[lo];
            nums[lo] = nums[hi];
            nums[hi] = tmp;
            lo++;
            hi--;
        }
    }

    public static void main(String[] args) {
        int[] nums = {1,2,3,4,5,6,7};
        int k = 3;
        System.out.printf("%s => ", Arrays.toString(nums));
        rotate(nums, k);
        System.out.printf("%s%n", Arrays.toString(nums));
    }
}
