/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MinimumFallingPathSum;

public class App {
    public static void main(String[] args) {
        int[][] matrix = {{-19,57},{-40,-5}};
        DPSolution dpSolution = new DPSolution();
        int minSum = dpSolution.minFallingPathSum(matrix);
        System.out.printf("minSum: %d%n", minSum);

        SpaceOptimizedDPSolution spaceOptimizedDPSolution = new SpaceOptimizedDPSolution();
        minSum = spaceOptimizedDPSolution.minFallingPathSum(matrix);
        System.out.printf("minSum: %d%n", minSum);
    }
}
