/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MinimumASCIIDeleteSumForTwoStrings;

public class App {
    public static void main(String[] args) {
        String s1 = "delete";
        String s2 = "leet";

        DPSolution dpSolution = new DPSolution();
        int minimumDeleteSum = dpSolution.minimumDeleteSum(s1, s2);
        String lcs = dpSolution.lcs(s1, s2);
        System.out.printf("Minimum delete sum: %d, lcs: %s%n", minimumDeleteSum, lcs);
    }
}
