/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SearchInRotatedSortedArrayII;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] nums = {2,5,6,0,0,1,2};
        int target = 0;
        Solution solution = new Solution();
        if (solution.search(nums, target)) {
            System.out.printf("%d exists in %s%n", target, Arrays.toString(nums));
        } else {
            System.out.printf("%d doesn't exist in %s%n", target, Arrays.toString(nums));
        }
    }
}
