/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LongestIncreasingSubsequence;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] nums = {10, 9, 2, 5, 3, 7, 101, 18};
        DPSolution dpSolution = new DPSolution();
        int longest = dpSolution.lengthOfLIS(nums);
        System.out.printf("nums: %s, longest: %d%n", Arrays.toString(nums), longest);
        System.out.printf("seq: %s%n", dpSolution.lis(nums));

        BetterSolution betterSolution = new BetterSolution();
        longest = betterSolution.lengthOfLIS(nums);
        System.out.printf("nums: %s, longest: %d%n", Arrays.toString(nums), longest);
    }
}
