/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MaximalSquare;

public class App {
    public static void main(String[] args) {
        char[][] matrix = {
                {'1','0','1','0','0'},
                {'1','0','1','1','1'},
                {'1','1','1','1','1'},
                {'1','0','0','1','0'},
        };

        Solution solution = new Solution();
        int maxArea = solution.maximalSquare(matrix);
        System.out.printf("Max area: %d%n", maxArea);
    }
}
