/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RemoveDigitFromNumberToMaximizeResult;

public class App {
    public static void main(String[] args) {
        String number = "1325353";
        char digit = '3';
        Solution solution = new Solution();
        String result = solution.removeDigit(number, digit);
        System.out.printf("%s => %s%n", number, result);
    }
}
