/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WaysToAssignUniqueCap;

public class App {
    public static void main(String[] args) {
        int[][] caps = {
                {3, 4, 1},
                {2},
                {3, 4},
        };
        Solution solution = new Solution();
        int result = solution.assignUniqueCap(caps);
        System.out.printf("%d ways to assign unique caps for %d people%n", result, caps.length);
    }
}
