/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SearchInRotatedSortedArray;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] nums = {4,5,6,7,0,1,2};
        int target = 0;
        Solution solution = new Solution();
        int index = solution.search(nums, target);
        System.out.printf("%s, target: %d. index: %d%n", Arrays.toString(nums), target, index);
    }
}
