/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CoinChange;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] coins = {1, 2, 5};
        int amount = 11;

        Solution solution = new Solution();
        int count = solution.coinChange(coins, amount);
        System.out.printf("coins: %s, amount: %d, count: %d\n", Arrays.toString(coins), amount, count);
    }
}
