#!/usr/bin/env ruby


COINS = [1, 3, 5]

def coins(target)
    d = [0]
    for i in 1..(target-1)
        tmp = []
        for j in 0..2
            if COINS[j] > i
                tmp[j] = 9999999
        end
    end
end
