/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BestTimeToBuyAndSellStockII;

import java.lang.reflect.Array;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[][] a = test();
        for (int[] n : a) {
            System.out.println(Arrays.toString(n));
        }
    }

    private static int[][] test() {
        return new int[][] {
                {3, 4},
                {7, 8},
        };
    }
}
