/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LongestCommonSubsequence;

import java.util.List;

public class App {
    public static void main(String[] args) {
        String text1 = "idixdiuozt";
        String text2 = "iqdqiwotv";
        DPSolution dpSolution = new DPSolution();
        int lcsLength = dpSolution.longestCommonSubsequence(text1, text2);
        List<Character> lcs = dpSolution.buildLCSFromDP(text1, text2);
        System.out.printf("lcs: %s, length: %d%n", lcs, lcsLength);
    }
}
