/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PalindromicSubstrings;

public class App {

    public static void main(String[] args) {
        String a = "aaa";
        Solution solution = new Solution();
        int count = solution.countSubstrings(a);
        System.out.printf("Number of palindromic substrings: %d%n", count);
    }
}
