/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MedianOfTwoSortedArrays;

public class App {
    public static void main(String[] args) {
        int l = 0, r = -1;
        System.out.println((l + r) / 2);
        System.out.println((int) Math.floor((l + r) / 2.0));
    }
}
